### ISSUE TITLE
How to support multiple databases

### ISSUE THREAD

**Issue by JeniTurtle** [goldcaddy77/warthog#273] opened 2019-12-05 10:01 UTC
How to support multiple databases

**Comment by goldcaddy77** [comment] 2019-12-05 14:06
Hi @JeniTurtle , I’m not currently supporting multiple databases so that I can check all of the boxes for Postgres first. What database do you want to use?

**Comment by JeniTurtle** [comment] 2019-12-05 14:11
I like postgres！

**Comment by goldcaddy77** [comment] 2019-12-05 14:38
Cool, then you’re all set!

**Comment by goldcaddy77** [comment] 2019-12-12 03:11
Closing as dupe of https://github.com/goldcaddy77/warthog/issues/96

**Closed by goldcaddy77** 2019-12-12 03:11 UTC
